server:
  port: 8002
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
  application:
    name: order-client
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 10 #eureka client发送心跳给server端后，续 约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 5 #发送心跳续约间隔
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    #设置显示 实例id的ip信息
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka1:9000/eureka,http://eureka2:9001/eureka
# 自定义负载均衡策略为随机
product-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    ReadTimeout: 5000
#    ConnectTimeout: 5000
feign:
  sentinel:
    #开启基于sentinel的服务熔断
    enabled: true
  client:
    config:
      product-server:
        logger-level: FULL
        connectTimeout: 50000
        readTimeout: 50000
#  hystrix:
#    enabled: true
#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        requestVolumeThreshold: 5
#        sleepWindowInMilliseconds: 10000
#        errorThresholdPercentage: 50
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
logging:
  level:
    com.pansky.order.service.ProductService: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'

